### ISSUE TITLE
Automatically give user permission

### ISSUE THREAD

**Issue by mholttech** [macadmins/sal-ldap#1]
I got LDAP working but in order to actually give the account permission I have to log in with the account then log out and back in with the admin user in order to grant the user access to sal? is there any way to automatically do this based on group membership?

**Comment by grahamgilbert** [comment]
Not presently, and I don't need this. Will accept pull requests though. It would probably be easiest to extend the API to achieve this, as it would require a fair bit of plumbing to link Business Units to groups (from LDAP or internal Django groups) - either way, this would be an issue for Sal, as this is just the Docker container.
